-- Inserts para TB_CADASTRO
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (1, DATE '2005-08-15', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (1, DATE '2012-04-20', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (1, DATE '2020-09-10', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (2, DATE '1999-07-30', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (2, DATE '2023-01-01', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (3, DATE '1985-03-10', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (3, DATE '1995-05-12', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (3, DATE '2000-10-25', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (3, DATE '2008-12-19', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (3, DATE '2024-05-10', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (4, DATE '2022-06-15', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (5, DATE '2010-11-11', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (6, DATE '1990-03-03', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (6, DATE '2019-07-09', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (7, DATE '2023-03-17', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (8, DATE '2001-01-01', 'Inativa');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (8, DATE '2020-02-29', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (9, DATE '2023-12-12', 'Ativa');

INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (10, DATE '2024-01-20', 'Ativa');

-- ID_PESSOA 11 (3 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (11, DATE '2000-02-14', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (11, DATE '2008-09-01', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (11, DATE '2023-06-20', 'ativo');

-- ID_PESSOA 12 (2 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (12, DATE '2015-04-04', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (12, DATE '2024-10-10', 'ativo');

-- ID_PESSOA 13 (4 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (13, DATE '2001-11-25', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (13, DATE '2006-06-30', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (13, DATE '2013-08-18', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (13, DATE '2021-01-01', 'ativo');

-- ID_PESSOA 14 (1 cadastro, ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (14, DATE '2022-02-02', 'ativo');

-- ID_PESSOA 15 (2 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (15, DATE '2005-07-07', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (15, DATE '2023-09-09', 'ativo');

-- ID_PESSOA 16 (5 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (16, DATE '1998-03-03', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (16, DATE '2003-12-12', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (16, DATE '2010-10-10', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (16, DATE '2016-06-06', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (16, DATE '2022-11-11', 'ativo');

-- ID_PESSOA 17 (3 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (17, DATE '2012-05-15', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (17, DATE '2018-08-08', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (17, DATE '2023-03-03', 'ativo');

-- ID_PESSOA 18 (4 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (18, DATE '1997-01-01', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (18, DATE '2007-07-07', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (18, DATE '2017-12-12', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (18, DATE '2025-01-01', 'ativo');

-- ID_PESSOA 19 (2 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (19, DATE '2002-02-20', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (19, DATE '2022-02-20', 'ativo');

-- ID_PESSOA 20 (4 cadastros, 1 ativo)
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (20, DATE '1999-09-09', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (20, DATE '2009-09-09', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (20, DATE '2019-09-09', 'inativo');
INSERT INTO TB_CADASTRO (ID_PESSOA, DT_CADASTRO, STATUS) VALUES (20, DATE '2024-09-09', 'ativo');
