--inserts

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (1, 'Rua Gaivota', '101', 'Apto 11', 'Moema', 'São Paulo', 'SP', '04571000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (2, 'Rua Gaivota', '105', '', 'Moema', 'São Paulo', 'SP', '04571000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (3, 'Avenida Cotovia', '12', 'Casa 2', 'Moema', 'São Paulo', 'SP', '04524001', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (4, 'Rua Canário', '345', '', 'Moema', 'São Paulo', 'SP', '04521002', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (5, 'Rua Vergueiro', '800', 'Bloco B', 'Vila Mariana', 'São Paulo', 'SP', '04101000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (6, 'Rua Domingos de Morais', '1550', 'Apto 34', 'Vila Mariana', 'São Paulo', 'SP', '04010000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (7, 'Rua Afonso Celso', '220', '', 'Vila Mariana', 'São Paulo', 'SP', '04119001', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (8, 'Rua Pelotas', '78', 'Casa 4', 'Vila Mariana', 'São Paulo', 'SP', '04012000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (9, 'Rua dos Pinheiros', '1100', '', 'Pinheiros', 'São Paulo', 'SP', '05422001', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (10, 'Rua Artur de Azevedo', '902', 'Apto 8', 'Pinheiros', 'São Paulo', 'SP', '05404001', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (11, 'Rua Cardeal Arcoverde', '560', '', 'Pinheiros', 'São Paulo', 'SP', '05408000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (12, 'Rua Mateus Grou', '220', 'Casa 1', 'Pinheiros', 'São Paulo', 'SP', '05415010', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (13, 'Rua Coelho Lisboa', '400', '', 'Tatuapé', 'São Paulo', 'SP', '03325000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (14, 'Rua Itapura', '123', '', 'Tatuapé', 'São Paulo', 'SP', '03310000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (15, 'Rua Apucarana', '78', 'Bloco C', 'Tatuapé', 'São Paulo', 'SP', '03311000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (16, 'Rua Serra de Japi', '900', '', 'Tatuapé', 'São Paulo', 'SP', '03309010', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (17, 'Rua Gaivota', '202', '', 'Moema', 'São Paulo', 'SP', '04571000', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (18, 'Rua Afonso Celso', '300', 'Apto 6', 'Vila Mariana', 'São Paulo', 'SP', '04119001', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (19, 'Rua Artur de Azevedo', '980', '', 'Pinheiros', 'São Paulo', 'SP', '05404001', 'Residencial');

INSERT INTO TB_ENDERECO (ID_PESSOA, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO_ENDERECO) 
VALUES (20, 'Rua Itapura', '200', 'Apto 3', 'Tatuapé', 'São Paulo', 'SP', '03310000', 'Residencial');
